-- ═══════════════════════════════════════════════════════════
-- CartaMaster — Schema completo de base de datos
-- ───────────────────────────────────────────────────────────
-- INSTRUCCIONES:
--   • Instalación limpia (sin datos previos):
--       Descomenta el bloque DROP al inicio, luego ejecuta todo.
--   • Base de datos ya existente con datos:
--       Ejecuta solo desde la línea "CREATE TABLE IF NOT EXISTS"
--       hacia abajo. Las tablas existentes no se recrearán, pero
--       sí se crearán las que falten (usuarios, audit_log).
-- ═══════════════════════════════════════════════════════════

-- ── (Opcional) Borrar todo para instalación limpia ───────────
-- ADVERTENCIA: ELIMINA TODOS LOS DATOS. Descomenta solo si es una
-- instalación nueva o en un entorno de prueba.
/*
DROP TABLE IF EXISTS audit_log        CASCADE;
DROP TABLE IF EXISTS gestiones        CASCADE;
DROP TABLE IF EXISTS cotizaciones     CASCADE;
DROP TABLE IF EXISTS abonos           CASCADE;
DROP TABLE IF EXISTS pagos            CASCADE;
DROP TABLE IF EXISTS creditos         CASCADE;
DROP TABLE IF EXISTS clientes         CASCADE;
DROP TABLE IF EXISTS usuarios         CASCADE;
DROP TABLE IF EXISTS plantillas       CASCADE;
DROP TABLE IF EXISTS historial_meses  CASCADE;
DROP TABLE IF EXISTS config           CASCADE;
*/

-- ── Clientes de cartera ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS clientes (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
  nombre              TEXT NOT NULL,
  contacto            TEXT,
  estado              TEXT DEFAULT 'Cotizado',
  fecha_cotizacion    DATE,
  fecha_notificacion  DATE,
  fecha_pago          DATE,
  fecha_facturacion   DATE,
  fecha_suspension    DATE,
  mes                 TEXT,
  anio                TEXT,
  monto               DECIMAL(15,2),
  comentario          TEXT,
  nota                TEXT,
  suspendido          BOOLEAN DEFAULT FALSE,
  tags                JSONB DEFAULT '[]',
  historial           JSONB DEFAULT '[]',
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ── Pagos registrados por cliente ────────────────────────────
CREATE TABLE IF NOT EXISTS pagos (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
  cliente_id      BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  cliente_nombre  TEXT DEFAULT '',
  monto           DECIMAL(15,2) NOT NULL,
  fecha           TIMESTAMPTZ DEFAULT NOW(),
  fecha_formato   TEXT DEFAULT '',
  fecha_pago      DATE,
  banco           TEXT DEFAULT '',
  referencia      TEXT DEFAULT '',
  tipo_negocio    TEXT DEFAULT '',
  nota            TEXT,
  estado          TEXT DEFAULT 'pendiente',
  creado_por      TEXT DEFAULT '',
  empresa_id      BIGINT,
  validado_por    TEXT,
  validado_en     TIMESTAMPTZ,
  motivo_rechazo  TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── Créditos / préstamos ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS creditos (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
  numero_orden      TEXT,
  cliente           TEXT NOT NULL,
  monto             DECIMAL(15,2),
  fecha_inicio      DATE,
  plazo_meses       INTEGER,
  fecha_vencimiento DATE,
  fecha_pago_c      DATE,
  estado            TEXT DEFAULT 'Activo',
  comentario        TEXT,
  historial         JSONB DEFAULT '[]',
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- ── Abonos a créditos ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS abonos (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
  credito_id    BIGINT NOT NULL REFERENCES creditos(id) ON DELETE CASCADE,
  monto         DECIMAL(15,2) NOT NULL,
  fecha         TIMESTAMPTZ DEFAULT NOW(),
  fecha_formato TEXT DEFAULT '',
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ── Documentos / Cotizaciones PDF (base64) ───────────────────
CREATE TABLE IF NOT EXISTS cotizaciones (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
  cliente_id  BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  nombre      TEXT NOT NULL,
  datos       TEXT,           -- base64 del PDF
  monto       DECIMAL(15,2),
  fecha       TIMESTAMPTZ DEFAULT NOW(),
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── Bitácora de gestiones de cobro ───────────────────────────
CREATE TABLE IF NOT EXISTS gestiones (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
  cliente_id    BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  fecha         TIMESTAMPTZ DEFAULT NOW(),
  tipo          TEXT,
  resultado     TEXT,
  nota          TEXT,
  proxima_fecha DATE,
  usuario       TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ── Plantillas de WhatsApp ───────────────────────────────────
CREATE TABLE IF NOT EXISTS plantillas (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
  nombre     TEXT NOT NULL,
  texto      TEXT NOT NULL,
  orden      INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Snapshots mensuales (historial de meses) ─────────────────
CREATE TABLE IF NOT EXISTS historial_meses (
  mes_key    TEXT PRIMARY KEY,   -- ej: "2026-01"
  datos      JSONB NOT NULL,     -- { clientes: [...], creditos: [...] }
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Configuración y preferencias del sistema ─────────────────
CREATE TABLE IF NOT EXISTS config (
  clave      TEXT PRIMARY KEY,
  valor      TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Usuarios (autenticación con NextAuth) ────────────────────
-- Manejados por security.js — NO borrar ni modificar manualmente.
CREATE TABLE IF NOT EXISTS usuarios (
  username   TEXT PRIMARY KEY,
  pass       TEXT NOT NULL,                -- hash bcrypt
  rol        TEXT NOT NULL DEFAULT 'viewer'
               CHECK (rol IN ('admin', 'editor', 'viewer')),
  nombre     TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Audit log (bitácora de accesos y eventos) ────────────────
-- Insertado automáticamente por security.js — solo lectura para admins.
CREATE TABLE IF NOT EXISTS audit_log (
  id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ts       TIMESTAMPTZ DEFAULT NOW(),
  action   TEXT,
  username TEXT,
  ip       TEXT,
  extra    TEXT
);

-- ═══════════════════════════════════════════════════════════
-- Relaciones (resumen visual):
--
--   clientes ──< pagos        (1 cliente → N pagos)
--   clientes ──< cotizaciones (1 cliente → N documentos PDF)
--   clientes ──< gestiones    (1 cliente → N gestiones de cobro)
--   creditos ──< abonos       (1 crédito → N abonos)
--
--   usuarios     → autenticación de sistema (independiente)
--   audit_log    → registro de eventos (independiente)
--   historial_meses → snapshots mensuales (independiente)
--   config       → parámetros del sistema (independiente)
--   plantillas   → textos WhatsApp (independiente)
-- ═══════════════════════════════════════════════════════════

-- ── Índices para consultas frecuentes ────────────────────────
CREATE INDEX IF NOT EXISTS idx_pagos_cliente        ON pagos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_abonos_credito       ON abonos(credito_id);
CREATE INDEX IF NOT EXISTS idx_cotizaciones_cliente ON cotizaciones(cliente_id);
CREATE INDEX IF NOT EXISTS idx_gestiones_cliente    ON gestiones(cliente_id);
CREATE INDEX IF NOT EXISTS idx_clientes_estado      ON clientes(estado);
CREATE INDEX IF NOT EXISTS idx_creditos_estado      ON creditos(estado);
CREATE INDEX IF NOT EXISTS idx_audit_log_ts         ON audit_log(ts DESC);

-- ── Deshabilitar RLS ──────────────────────────────────────────
-- La autenticación se maneja con NextAuth en las API routes.
-- El service_role key bypassa RLS de todas formas.
ALTER TABLE clientes        DISABLE ROW LEVEL SECURITY;
ALTER TABLE pagos           DISABLE ROW LEVEL SECURITY;
ALTER TABLE creditos        DISABLE ROW LEVEL SECURITY;
ALTER TABLE abonos          DISABLE ROW LEVEL SECURITY;
ALTER TABLE cotizaciones    DISABLE ROW LEVEL SECURITY;
ALTER TABLE gestiones       DISABLE ROW LEVEL SECURITY;
ALTER TABLE plantillas      DISABLE ROW LEVEL SECURITY;
ALTER TABLE historial_meses DISABLE ROW LEVEL SECURITY;
ALTER TABLE config          DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios        DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log       DISABLE ROW LEVEL SECURITY;

-- ── Datos iniciales de configuración ─────────────────────────
INSERT INTO config (clave, valor) VALUES
  ('meta_mensual',     '0'),
  ('color_acento',     '#635bff'),
  ('recordatorio_dias','7'),
  ('modo_compacto',    'false')
ON CONFLICT (clave) DO NOTHING;

-- ═══════════════════════════════════════════════════════════
-- MIGRACIÓN: Si las tablas YA EXISTEN sin auto-incremento,
-- ejecuta este bloque separado para agregar las secuencias:
-- ═══════════════════════════════════════════════════════════
/*
DO $$
DECLARE
  seq_val BIGINT;
BEGIN
  -- clientes
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'clientes_id_seq') THEN
    CREATE SEQUENCE clientes_id_seq START 10000;
    ALTER TABLE clientes ALTER COLUMN id SET DEFAULT nextval('clientes_id_seq');
    SELECT GREATEST(COALESCE(MAX(id), 9999) + 1, 10000) INTO seq_val FROM clientes;
    PERFORM setval('clientes_id_seq', seq_val);
  END IF;

  -- pagos
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'pagos_id_seq') THEN
    CREATE SEQUENCE pagos_id_seq START 10000;
    ALTER TABLE pagos ALTER COLUMN id SET DEFAULT nextval('pagos_id_seq');
    SELECT GREATEST(COALESCE(MAX(id), 9999) + 1, 10000) INTO seq_val FROM pagos;
    PERFORM setval('pagos_id_seq', seq_val);
  END IF;

  -- creditos
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'creditos_id_seq') THEN
    CREATE SEQUENCE creditos_id_seq START 10000;
    ALTER TABLE creditos ALTER COLUMN id SET DEFAULT nextval('creditos_id_seq');
    SELECT GREATEST(COALESCE(MAX(id), 9999) + 1, 10000) INTO seq_val FROM creditos;
    PERFORM setval('creditos_id_seq', seq_val);
  END IF;

  -- abonos
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'abonos_id_seq') THEN
    CREATE SEQUENCE abonos_id_seq START 10000;
    ALTER TABLE abonos ALTER COLUMN id SET DEFAULT nextval('abonos_id_seq');
    SELECT GREATEST(COALESCE(MAX(id), 9999) + 1, 10000) INTO seq_val FROM abonos;
    PERFORM setval('abonos_id_seq', seq_val);
  END IF;

  -- cotizaciones
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'cotizaciones_id_seq') THEN
    CREATE SEQUENCE cotizaciones_id_seq START 10000;
    ALTER TABLE cotizaciones ALTER COLUMN id SET DEFAULT nextval('cotizaciones_id_seq');
    SELECT GREATEST(COALESCE(MAX(id), 9999) + 1, 10000) INTO seq_val FROM cotizaciones;
    PERFORM setval('cotizaciones_id_seq', seq_val);
  END IF;
END $$;
*/
