UPDATE clientes SET codigo_cliente = 3344 WHERE UPPER(TRIM(nombre)) = 'MARTIRE PINEDA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 606 WHERE UPPER(TRIM(nombre)) = 'ABEL GALVEZ LAZALA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1451 WHERE UPPER(TRIM(nombre)) = 'ABEL VALERIO CARO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 4011 WHERE UPPER(TRIM(nombre)) = 'ADAMES ME RED SRL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1715 WHERE UPPER(TRIM(nombre)) = 'ADRIANO MOREL GUZMAN' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 563 WHERE UPPER(TRIM(nombre)) = 'ALAN SOLUCIONES SRL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1558 WHERE UPPER(TRIM(nombre)) = 'ALEJANDRO QUIROZ ESCOLASTICO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1491 WHERE UPPER(TRIM(nombre)) = 'AMAURY ANTONIO RODRIGUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3288 WHERE UPPER(TRIM(nombre)) = 'ANA YSABEL ESTEVEZ RODRIGUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3160 WHERE UPPER(TRIM(nombre)) = 'ANDERSON SANTOS DE LOS SANTOS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3228 WHERE UPPER(TRIM(nombre)) = 'ANEURIS TORIBIO ALCANTARA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5061 WHERE UPPER(TRIM(nombre)) = 'ANGELO JOSE RODRIGUEZ RODRIGUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1650 WHERE UPPER(TRIM(nombre)) = 'ANNE CONTRERAS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3226 WHERE UPPER(TRIM(nombre)) = 'ANNIE STEPHANIE DE LA CRUZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1196 WHERE UPPER(TRIM(nombre)) = 'ANYELO EMILIO SANCHEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3330 WHERE UPPER(TRIM(nombre)) = 'ARISMENDY PLASENCIO MARTINEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 639 WHERE UPPER(TRIM(nombre)) = 'ARLEY BERNABEL MELO (BANCAS YAMILEY)' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1556 WHERE UPPER(TRIM(nombre)) = 'AUDRIS MILENA PUENTE' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1561 WHERE UPPER(TRIM(nombre)) = 'AUGUSTO NAATANIEL RODRIGUEZ SOSA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 568 WHERE UPPER(TRIM(nombre)) = 'BANCAS CORONA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 154 WHERE UPPER(TRIM(nombre)) = 'BANCAS EL SOL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 476 WHERE UPPER(TRIM(nombre)) = 'BANCAS SV' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1116 WHERE UPPER(TRIM(nombre)) = 'BERNIS MAIRENI BATISTA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 102 WHERE UPPER(TRIM(nombre)) = 'CARLOS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 275 WHERE UPPER(TRIM(nombre)) = 'CARLOS FERNANDEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3264 WHERE UPPER(TRIM(nombre)) = 'CARLOS MANUEL HENRIQUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5140 WHERE UPPER(TRIM(nombre)) = 'CARLOS VALENTIN REGALADO RIVERA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5152 WHERE UPPER(TRIM(nombre)) = 'CARMEN RAMONA ALCANTARA VELOZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3120 WHERE UPPER(TRIM(nombre)) = 'CECILIA MARIANO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 167 WHERE UPPER(TRIM(nombre)) = 'CEDENO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3225 WHERE UPPER(TRIM(nombre)) = 'CESAR DANIEL GONZALEZ QUEZADA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5221 WHERE UPPER(TRIM(nombre)) = 'CLAIRE SANDE CUEVAS MONTAS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5206 WHERE UPPER(TRIM(nombre)) = 'CONFESOR ARAUJO EMETERIO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1582 WHERE UPPER(TRIM(nombre)) = 'CONSORCIO DE BANCAS S A B SRL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3323 WHERE UPPER(TRIM(nombre)) = 'CRISTIAN ARIEL ALLADEEN DOMINGUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3122 WHERE UPPER(TRIM(nombre)) = 'CRISTIAN JOSE EUSEBIO RODRIGUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5207 WHERE UPPER(TRIM(nombre)) = 'CRUCITO SANTOS GUZMAN' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1610 WHERE UPPER(TRIM(nombre)) = 'DALVELT DELFO MONTERO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 793 WHERE UPPER(TRIM(nombre)) = 'DANULO DE LEON' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1502 WHERE UPPER(TRIM(nombre)) = 'DANY JANIEL BAEZ CORNIEL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1448 WHERE UPPER(TRIM(nombre)) = 'DARWIN GERMAN LOPEZ CANARIO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5208 WHERE UPPER(TRIM(nombre)) = 'DELVI JOSE RODRIGUEZ TAVERAS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3261 WHERE UPPER(TRIM(nombre)) = 'DIONICIO GENARO LOPEZ GOMEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1174 WHERE UPPER(TRIM(nombre)) = 'DIONIRYS SANELY BATISTA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5222 WHERE UPPER(TRIM(nombre)) = 'DONALD CAILLOT' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 957 WHERE UPPER(TRIM(nombre)) = 'EDWARD DE LEON' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1167 WHERE UPPER(TRIM(nombre)) = 'EDWTKON GAME Y PRESTAMOS SRL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1205 WHERE UPPER(TRIM(nombre)) = 'ELVIN REYES TUBURCIO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3133 WHERE UPPER(TRIM(nombre)) = 'EMELIN MENDEZ VARGAS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 214 WHERE UPPER(TRIM(nombre)) = 'ERICK' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 564 WHERE UPPER(TRIM(nombre)) = 'ERNESTO MARCELINO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1453 WHERE UPPER(TRIM(nombre)) = 'ERY DANIEL CUELLO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1317 WHERE UPPER(TRIM(nombre)) = 'ESTUVER LOPEZ CESPEDES' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5196 WHERE UPPER(TRIM(nombre)) = 'EVE RACHEL GERALDO CUELLO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1704 WHERE UPPER(TRIM(nombre)) = 'EZEQUIEL CARELA MORETA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5111 WHERE UPPER(TRIM(nombre)) = 'FAUSTINO CAPELLAN' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5195 WHERE UPPER(TRIM(nombre)) = 'FELIPE ANTONIO CRUZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5063 WHERE UPPER(TRIM(nombre)) = 'FELIX BENJAMIN PEREZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1634 WHERE UPPER(TRIM(nombre)) = 'FELIX CASTILLO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1111 WHERE UPPER(TRIM(nombre)) = 'FELIX MANUEL PLACENCIO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1564 WHERE UPPER(TRIM(nombre)) = 'FERNANDO HERNANDEZ SANTANA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1747 WHERE UPPER(TRIM(nombre)) = 'FRAN ROBERT CASADO TRONCOSO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 4067 WHERE UPPER(TRIM(nombre)) = 'FRANCIS ADALBERTO DE LEON ANTUNA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1746 WHERE UPPER(TRIM(nombre)) = 'FRANCISCO ANTONIO SANCHEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3152 WHERE UPPER(TRIM(nombre)) = 'FRANKLIN ESMIT PEREZ ORTIZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3271 WHERE UPPER(TRIM(nombre)) = 'FRANKLIN LUIS HEREDIA FERRERAS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 433 WHERE UPPER(TRIM(nombre)) = 'FREDY CLASE' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5223 WHERE UPPER(TRIM(nombre)) = 'GEISY OGANDO DE LOS SANTOS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5197 WHERE UPPER(TRIM(nombre)) = 'GERALD BLADIMIR BERIHUETE ALCANTARA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1599 WHERE UPPER(TRIM(nombre)) = 'GERALDSON EMIL CASADO SOTO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5066 WHERE UPPER(TRIM(nombre)) = 'GEURY MIGUEL TRONCOSO ORTIZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5112 WHERE UPPER(TRIM(nombre)) = 'GLINERYS LISBET ARIAS SANCHEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3090 WHERE UPPER(TRIM(nombre)) = 'GRUPO CJR RODRIGUEZ SRL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 46 WHERE UPPER(TRIM(nombre)) = 'GRUPO MARCAST' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1628 WHERE UPPER(TRIM(nombre)) = 'HENDRICH SANCHEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1446 WHERE UPPER(TRIM(nombre)) = 'HIPOLITO CORDERO POLANCO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3230 WHERE UPPER(TRIM(nombre)) = 'HONEISI OGANDO ENCARNACION' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5137 WHERE UPPER(TRIM(nombre)) = 'HORACIO VASQUEZ LIRANZO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5198 WHERE UPPER(TRIM(nombre)) = 'IVAN ERNESTO UCETA CARRASCO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3224 WHERE UPPER(TRIM(nombre)) = 'JAICEN VALERIO FONDEUR' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5180 WHERE UPPER(TRIM(nombre)) = 'JEFRY MANUEL CORPORAN DE LA ROSA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1592 WHERE UPPER(TRIM(nombre)) = 'JERRY AGENA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3287 WHERE UPPER(TRIM(nombre)) = 'JHONNY RIGOBERTO MEDINA ALCANTARA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1449 WHERE UPPER(TRIM(nombre)) = 'JOEL SMERLYN DIAZ PEREZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1415 WHERE UPPER(TRIM(nombre)) = 'JOHAN ESTIL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3322 WHERE UPPER(TRIM(nombre)) = 'JOHN CALVIN TOLENTINO MONTERO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 953 WHERE UPPER(TRIM(nombre)) = 'JONATHAN PEREZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3295 WHERE UPPER(TRIM(nombre)) = 'JORGE LUIS MOSQUEA PEREZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3159 WHERE UPPER(TRIM(nombre)) = 'JOSE ANTONIO DIAZ DIAZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 249 WHERE UPPER(TRIM(nombre)) = 'JOSE ANTONIO DIAZ DIAZ (BANCA JOSE)' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1479 WHERE UPPER(TRIM(nombre)) = 'JOSE DAVID MENDEZ DE LEON' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 212 WHERE UPPER(TRIM(nombre)) = 'JOSE FRANCISCO SANTOS CAMINERO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 651 WHERE UPPER(TRIM(nombre)) = 'JOSE MIGUEL ROSARIO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3331 WHERE UPPER(TRIM(nombre)) = 'JOSE SANTIAGO MATEO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 720 WHERE UPPER(TRIM(nombre)) = 'JOSELITO ANDRES SEVERINO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1417 WHERE UPPER(TRIM(nombre)) = 'JUAN ARIEL TAVAREZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3193 WHERE UPPER(TRIM(nombre)) = 'JUAN DANIEL GERONIMO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3177 WHERE UPPER(TRIM(nombre)) = 'JUAN JOSE RODRIGUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3332 WHERE UPPER(TRIM(nombre)) = 'JULIO ALBERTO VALDEZ FELIX' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3251 WHERE UPPER(TRIM(nombre)) = 'JULIO CESAR MARTINEZ MATEO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3321 WHERE UPPER(TRIM(nombre)) = 'JULIO ENCARNACION' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3306 WHERE UPPER(TRIM(nombre)) = 'JULIO SAURY MELLA FELIZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5157 WHERE UPPER(TRIM(nombre)) = 'KATHERINNE SILVANIA CARREÑO RUIZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 956 WHERE UPPER(TRIM(nombre)) = 'KELLY ARIAS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5118 WHERE UPPER(TRIM(nombre)) = 'KELVIN FIGUEREO BELTRE' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 58 WHERE UPPER(TRIM(nombre)) = 'LAMILAGROSA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 234 WHERE UPPER(TRIM(nombre)) = 'LAUVA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1600 WHERE UPPER(TRIM(nombre)) = 'LEANDRO MARTIN CORPORAN JORGE' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3298 WHERE UPPER(TRIM(nombre)) = 'LEIBY HERNANDEZ REYES' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5110 WHERE UPPER(TRIM(nombre)) = 'LEOBARD VICTORIANO RAMIREZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3297 WHERE UPPER(TRIM(nombre)) = 'LEONARDO POLANCO CRUZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 2211 WHERE UPPER(TRIM(nombre)) = 'LESLIE NICOLLE MONTILLA MARCANO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1649 WHERE UPPER(TRIM(nombre)) = 'LUIS ALBERTO CASTILLO OGANDO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3117 WHERE UPPER(TRIM(nombre)) = 'LUIS ALBERTO FELIZ ACOSTA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3307 WHERE UPPER(TRIM(nombre)) = 'LUIS ALBERTO PEREZ CONTRERAS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5192 WHERE UPPER(TRIM(nombre)) = 'LUIS ALBERTO REYES VASQUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 2240 WHERE UPPER(TRIM(nombre)) = 'LUIS ALBERTO TORRES SILFA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5181 WHERE UPPER(TRIM(nombre)) = 'LUIS ANTONIO MORONTA MELO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1008 WHERE UPPER(TRIM(nombre)) = 'LUIS HIDALGO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5176 WHERE UPPER(TRIM(nombre)) = 'MAIRELY SANCHEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 64 WHERE UPPER(TRIM(nombre)) = 'MANUEL ANTONIO MARMOLEJOS MICHEL (RICA)' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3300 WHERE UPPER(TRIM(nombre)) = 'MANUEL EMILIO SOTO CASTILLO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3319 WHERE UPPER(TRIM(nombre)) = 'MANUEL MARIA GUZMAN PIÑA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3153 WHERE UPPER(TRIM(nombre)) = 'MARCOS DEYVI ALBERTO CASTRO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3087 WHERE UPPER(TRIM(nombre)) = 'MARIA SALOME BAEZ ALMANZAR' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 578 WHERE UPPER(TRIM(nombre)) = 'MARLON ORESTE CATALINA SANCHEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1177 WHERE UPPER(TRIM(nombre)) = 'MARTHA TORRES GIL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3285 WHERE UPPER(TRIM(nombre)) = 'MAXIMO ENRIQUE ALCANTARA BRITO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3343 WHERE UPPER(TRIM(nombre)) = 'MAYRA ALEJANDRA LIRIANO ALMANZAR' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3195 WHERE UPPER(TRIM(nombre)) = 'MELVIN ALEXIS LARA MELO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3301 WHERE UPPER(TRIM(nombre)) = 'MELVIN RAFAEL NATERA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 328 WHERE UPPER(TRIM(nombre)) = 'MELVIN ROBERT BREA GUERRERO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1684 WHERE UPPER(TRIM(nombre)) = 'MIGUEL ALEXANDER CABRERA RAMIREZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1705 WHERE UPPER(TRIM(nombre)) = 'MIGUEL ANGEL TAVERAS ESPINAL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1554 WHERE UPPER(TRIM(nombre)) = 'MILKELY YOSELIN FELIZ PEGUERO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3318 WHERE UPPER(TRIM(nombre)) = 'MOHAMMED SHEHADE ISMAIL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 142 WHERE UPPER(TRIM(nombre)) = 'NCASTILLO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1699 WHERE UPPER(TRIM(nombre)) = 'NIOVE VENECIA AYBAR VIZCAINO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 83 WHERE UPPER(TRIM(nombre)) = 'NIUDESKI' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3208 WHERE UPPER(TRIM(nombre)) = 'NORBERTO CEPEDA GARCIA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 322 WHERE UPPER(TRIM(nombre)) = 'OLMEDO DE JESUS PEREZ MARMOL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1635 WHERE UPPER(TRIM(nombre)) = 'ORLANDO ENRIQUE BRITO DOMINGUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1655 WHERE UPPER(TRIM(nombre)) = 'ORLANDO MEDINA DE LOS SANTOS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1642 WHERE UPPER(TRIM(nombre)) = 'OSCALINA MÉNDEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 4000 WHERE UPPER(TRIM(nombre)) = 'OSCAR ANTONIO DE LEON SERRANO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3252 WHERE UPPER(TRIM(nombre)) = 'PAPO PEREZ VASQUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3258 WHERE UPPER(TRIM(nombre)) = 'PEDRO ANTONIO BATISTA DOMINGUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1570 WHERE UPPER(TRIM(nombre)) = 'RAFAEL ANTONIO VENTURA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1616 WHERE UPPER(TRIM(nombre)) = 'RAFAEL ARIAS VALDEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 2182 WHERE UPPER(TRIM(nombre)) = 'RAFAEL ESTEVAN LACHAPEL BAEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 545 WHERE UPPER(TRIM(nombre)) = 'RAFAEL LEBRON SEGURA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5233 WHERE UPPER(TRIM(nombre)) = 'RAMON ANDRES RODRIGUEZ RODRIGUEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3275 WHERE UPPER(TRIM(nombre)) = 'RAMON ANTONIO OSORIA SUERO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 477 WHERE UPPER(TRIM(nombre)) = 'RAMON FERNANDEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5216 WHERE UPPER(TRIM(nombre)) = 'RAMON JIMENEZ DE LEON' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 802 WHERE UPPER(TRIM(nombre)) = 'RAMON MELO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5080 WHERE UPPER(TRIM(nombre)) = 'RAYDER RAMON MATEO ALCANTARA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 84 WHERE UPPER(TRIM(nombre)) = 'REDLINE' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3333 WHERE UPPER(TRIM(nombre)) = 'RENE CARABALLO DE LA ROSA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1627 WHERE UPPER(TRIM(nombre)) = 'RICARDO ALFREDO MARTINEZ DE JESUS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1482 WHERE UPPER(TRIM(nombre)) = 'RICARDO DE JESUS ESTEVEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1585 WHERE UPPER(TRIM(nombre)) = 'ROBERT ELIGIO RAMIREZ RAMIREZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3292 WHERE UPPER(TRIM(nombre)) = 'ROBERT LUIS GERMAN DE JESUS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1460 WHERE UPPER(TRIM(nombre)) = 'ROBERTO DEL CARMEN JAQUEZ ESCOTTO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3302 WHERE UPPER(TRIM(nombre)) = 'RODOLFO TAVERAS CARMONA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1688 WHERE UPPER(TRIM(nombre)) = 'ROGELIO GOMEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 25 WHERE UPPER(TRIM(nombre)) = 'ROGELIO POLINE BELLO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1744 WHERE UPPER(TRIM(nombre)) = 'ROSSI MAGDALENA BELLO TIBURCIO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5160 WHERE UPPER(TRIM(nombre)) = 'SANTA JACQUELINE LARA PEREZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1285 WHERE UPPER(TRIM(nombre)) = 'SATURNINO RODRIGUEZ TEJADA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1615 WHERE UPPER(TRIM(nombre)) = 'SERGIO CARVAJAL MEDINA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3259 WHERE UPPER(TRIM(nombre)) = 'TOMAS SANCHEZ SANTOS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 183 WHERE UPPER(TRIM(nombre)) = 'TONY' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5234 WHERE UPPER(TRIM(nombre)) = 'VIANKA PEREZ ALCANTARA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5156 WHERE UPPER(TRIM(nombre)) = 'VICTOR JUNIOR RODRIGUEZ JIMENEZ (BANCAS CR)' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 5135 WHERE UPPER(TRIM(nombre)) = 'VICTOR MANUEL BAEZ JOSE' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1370 WHERE UPPER(TRIM(nombre)) = 'VIRGEN QUISQUEYA PENA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3277 WHERE UPPER(TRIM(nombre)) = 'VIRGILIO ANTONIO DE LEON TOPAL' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 93 WHERE UPPER(TRIM(nombre)) = 'VIRGILIO SPORT' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3286 WHERE UPPER(TRIM(nombre)) = 'WADRI REYES ALCANTARA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3227 WHERE UPPER(TRIM(nombre)) = 'WAGNER ANTONIO REYES GRAHAM' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1027 WHERE UPPER(TRIM(nombre)) = 'WILFREDO MATOS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 2134 WHERE UPPER(TRIM(nombre)) = 'WILIS LEONIDAS DE LA ROSA BAEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1733 WHERE UPPER(TRIM(nombre)) = 'WILKIN JEOVANNY PUJOLS SANTANA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1993 WHERE UPPER(TRIM(nombre)) = 'WILLY JOEL FELIZ MEJIA' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 772 WHERE UPPER(TRIM(nombre)) = 'YANCARLOS MATOS MELO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 635 WHERE UPPER(TRIM(nombre)) = 'YANNA MATOS' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3293 WHERE UPPER(TRIM(nombre)) = 'YANNA ROSIO MATOS GERALDO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1639 WHERE UPPER(TRIM(nombre)) = 'YASIRIS RODRIGUEZ SUAZO' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 3289 WHERE UPPER(TRIM(nombre)) = 'YERLIN JOSE SANCHEZ' AND empresa_id = 1 AND codigo_cliente IS NULL;
UPDATE clientes SET codigo_cliente = 1543 WHERE UPPER(TRIM(nombre)) = 'YSRRAEL ANTONIO HERNANDEZ CASTILLO' AND empresa_id = 1 AND codigo_cliente IS NULL;